name: beaumont-shuttersandblindsltd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#424347'
    - '#649599'
    - '#e42628'
    - '#eb6164'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.9792382137384266
purpose: []
